### ISSUE TITLE
Cannot format .vue files

### ISSUE THREAD

**Issue by solumon** [ota-meshi/stylelint-config-standard-vue#7]
Hi!

>  I use stylelint-config-standard-vue to format .vue file
>  in <style lang= "SCSS" scoped></style> does not work, 
>  but <style lang= "SCSS" scoped></style> is fine.

devDependencies
```
"stylelint": "^14.5.3",
"stylelint-config-recess-order": "^3.0.0",
"stylelint-config-standard": "^25.0.0",
 "stylelint-config-standard-scss": "^3.0.0",
"stylelint-config-standard-vue": "^1.0.0",
```
.stylelintrc.js
```
module.exports = {
    extends: [
        'stylelint-config-recess-order',
        "stylelint-config-standard-scss",
        "stylelint-config-standard-vue/scss"
    ],
    rules: {
        "indentation": 4,
        'scss/at-import-partial-extension': null
    }
};
```

.vscode/settings.json
```
/// stylelint
    "css.validate": false,
    "less.validate": false,
    "scss.validate": false,
    "stylelint.validate": [
        "css",
        "less",
        "postcss",
        "scss",
        "vue",
        "sass"
    ],
"editor.codeActionsOnSave": {
        "source.fixAll": true,
        "source.fixAll.stylelint": true
    },
```
Please help. Thanks.

**Comment by ota-meshi** [comment]
Thank you for posting this issue.
I'm not sure what your problem is.  Can you share a minimal of your repository that can reproduce the problem?

**Comment by solumon** [comment]
In Vue Single File Components, Adding lang= "SCSS" to <style> tag , vscode plugin Styleint  doesn't work，I wrote a demo but it works, I don't know if my ESlint configuration is affected here

**Comment by ota-meshi** [comment]
There may be a problem with the dependency. Please install and try postcss and postcss-scss explicitly.

```bash
npm i -D postcss-scss@latest postcss@latest
```

**Comment by solumon** [comment]
Thank you very much for your reply, it has worked well

**Comment by solumon** [comment]
> There may be a problem with the dependency. Please install and try postcss and postcss-scss explicitly.
> 
> ```shell
> npm i -D postcss-scss@latest postcss@latest
> ```

As it's done, it's working fine, thank you very much
