### ISSUE TITLE
Unknown word (CssSyntaxError) in VSCode

### ISSUE THREAD

**Issue by Sky-star** [ota-meshi/stylelint-config-standard-vue#8]
show error in vscode, but not in terminal
![image](https://user-images.githubusercontent.com/6882646/163090587-dd5ba5d0-8750-4491-93db-4a5c5f4f9af9.png)
![image](https://user-images.githubusercontent.com/6882646/163090664-b93d6868-e39f-42b5-b461-4c37a7d12376.png)

package.json
```json
"devDependencies": {
    "postcss-html": "^1.3.1",
    "stylelint": "^14.6.1",
    "stylelint-config-standard-vue": "^1.0.0",
  },
```
lint syntax
```json
    "lint:style": "stylelint **/*.vue",
```
.stylelintrc.js
```js
module.exports = {
  extends: [
    "stylelint-config-standard-vue"
  ],
  customSyntax: "postcss-html",
};
```

**Comment by ota-meshi** [comment]
Thank you for posting issue.
I can't reproduce your problem. Please provide a minimal repository to reproduce the your problem.

**Comment by Sky-star** [comment]
thanks for help!

https://github.com/Sky-star/icms.git

when i use `npm run lint:style` it works in terminal, but still have error in my vscode.

i create `index.scss` for test, vccode doesn't show any notice,just like something wrong in my stylelint plugin

in settings.json
```json
 "stylelint.validate": [
    "css",
    "postcss",
    "vue",
    "scss",
    "sass"
  ],
  "stylelint.snippet": [
    "css",
    "postcss"
  ],
```

**Comment by ota-meshi** [comment]
Stylelint is not installed in your repository.

**Comment by Sky-star** [comment]
in `package.json` ?  or vscode stylelint plugin?

**Comment by ota-meshi** [comment]
https://github.com/Sky-star/icms/blob/main/package.json#L25

**Comment by Sky-star** [comment]
sorry, my fault
i get error in `git push`, please pull again.

**Comment by ota-meshi** [comment]
I have tried your repository but can't reproduce the your problem. How about removing node_modules and reinstalling it?
If that doesn't help, I don't know the cause.

terminal:

<img width="626" alt="image" src="https://user-images.githubusercontent.com/16508807/163115458-0f9e24de-7639-4ca1-9fa0-4b5e9047981c.png">

vscode:

<img width="768" alt="image" src="https://user-images.githubusercontent.com/16508807/163115556-4e7edc09-6e9e-492c-8572-4d5c8151d065.png">

**Comment by Sky-star** [comment]
i reslove this problem, in vscode stylelint plugin, if you add **Stylelint: Config** in `settings.json`,  it won't be work correct.
thanks for help, i'll close this issue
